/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteRyD;

import java.rmi.Naming;
import javax.swing.JTextArea;

/**
 *
 * @author razvanvc
 */
public class Monitor extends javax.swing.JFrame {

    /**
     * Creates new form Monitor
     */
    @SuppressWarnings({"LeakingThisInConstructor", "UseSpecificCatch", "CallToThreadStartDuringObjectConstruction"})
    public Monitor() {
        initComponents();

        LogRestaurante lr = new LogRestaurante("./evolucionRestauranteRMI.txt");
        Mostrador mp = new Mostrador(10, ta_MostradorPedidos);
        Mesa mesaPlatos = new Mesa(20, ta_MesaPlatos);
        //Creamos e iniciamos los 200 clientes
        //SUGERENCIA: Exportar todo esto a un metodo mas abajo
        for (int i = 1; i < 201; i++) {
            Cliente cv = new Cliente("Cliente" + i, mp, 2, lr);
            cv.start();
        }

        Empleado e1 = new Empleado("Empleado 1", mesaPlatos, mp, null, lr);
        e1.start();
        Empleado e2 = new Empleado("Empleado 2", mesaPlatos, mp, null, lr);
        e2.start();

        Cocinero c1 = new Cocinero("Cocinero 1", mesaPlatos, null, lr);
        Cocinero c2 = new Cocinero("Cocinero 2", mesaPlatos, null, lr);
        Cocinero c3 = new Cocinero("Cocinero 3", mesaPlatos, null, lr);

        c1.start();
        c2.start();
        c3.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_MostradorPedidos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_MesaPlatos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 470));
        setPreferredSize(new java.awt.Dimension(460, 500));

        ta_MostradorPedidos.setColumns(20);
        ta_MostradorPedidos.setRows(5);
        jScrollPane1.setViewportView(ta_MostradorPedidos);

        ta_MesaPlatos.setColumns(20);
        ta_MesaPlatos.setRows(5);
        jScrollPane2.setViewportView(ta_MesaPlatos);

        jLabel1.setText("Mostrador de pedidos:");

        jLabel2.setText("Mesa de platos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getjTextArea1() {
        return ta_MostradorPedidos;
    }

    public JTextArea getjTextArea2() {
        return ta_MesaPlatos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta_MesaPlatos;
    private javax.swing.JTextArea ta_MostradorPedidos;
    // End of variables declaration//GEN-END:variables

}
