/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestauranteRyD;

import javax.swing.JTextField;

/**
 *
 * @author razvanvc
 */
public class Restaurante_P1 extends javax.swing.JFrame {

    //Variables para modificar las sistemas
    private final int numeroPedidos = 2;
    private final int tamannoMostrador = 10;
    private final int MAX_TAMANNO_MESA = 20;
    private final Empleado e1;
    private final Empleado e2;
    private final Cocinero c1;
    private final Cocinero c2;
    private final Cocinero c3;
    /**
     * Creates new form Restaurante_P1
     */
    @SuppressWarnings("CallToThreadStartDuringObjectConstruction")
    public Restaurante_P1() {
        initComponents();
        
        Mostrador mp = new Mostrador(tamannoMostrador, ta_MostradorPedidos);
        Mesa mesaPlatos = new Mesa(MAX_TAMANNO_MESA, ta_MesaPlatos);
        //Creamos e iniciamos los 200 clientes
        //SUGERENCIA: Exportar todo esto a un metodo mas abajo
        for (int i = 1; i<202; i++){
            Cliente cv = new Cliente("Cliente"+i, mp, numeroPedidos);
            cv.start();
        }
        
        e1 = new Empleado("Empleado 1", mesaPlatos, mp, tf_Empleado1);
        e1.start();
        e2 = new Empleado("Empleado 2", mesaPlatos, mp, tf_Empleado2);
        e2.start();
        
        c1 = new Cocinero("Cocinero 1", mesaPlatos, tf_Cocinero1);
        c2 = new Cocinero("Cocinero 2", mesaPlatos, tf_Cocinero2);
        c3 = new Cocinero("Cocinero 3", mesaPlatos, tf_Cocinero3);
        
        c1.start();
        c2.start();
        c3.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Contenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_Empleado1 = new javax.swing.JTextField();
        tf_Empleado2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_Cocinero1 = new javax.swing.JTextField();
        tf_Cocinero3 = new javax.swing.JTextField();
        tf_Cocinero2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_MostradorPedidos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_MesaPlatos = new javax.swing.JTextArea();
        tb_EstadoEmpleado1 = new javax.swing.JToggleButton();
        tb_EstadoEmpleado2 = new javax.swing.JToggleButton();
        tb_EstadoSistema = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Contenido.setText("Contenido del mostrador de pedidos:");

        jLabel1.setText("Empleado 1:");

        jLabel2.setText("Empleado 2:");

        jLabel3.setText("Contenido de la mesa de platos:");

        jLabel4.setText("Cocinero 1:");

        jLabel5.setText("Cocinero 2:");

        jLabel6.setText("Cocinero 3:");

        ta_MostradorPedidos.setColumns(20);
        ta_MostradorPedidos.setRows(5);
        jScrollPane1.setViewportView(ta_MostradorPedidos);

        ta_MesaPlatos.setEditable(false);
        ta_MesaPlatos.setColumns(20);
        ta_MesaPlatos.setRows(5);
        jScrollPane2.setViewportView(ta_MesaPlatos);

        tb_EstadoEmpleado1.setText("Pausar Empleado 1");
        tb_EstadoEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_EstadoEmpleado1ActionPerformed(evt);
            }
        });

        tb_EstadoEmpleado2.setText("Pausar Empleado 2");
        tb_EstadoEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_EstadoEmpleado2ActionPerformed(evt);
            }
        });

        tb_EstadoSistema.setText("Pausar Sistema");
        tb_EstadoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_EstadoSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(lbl_Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(tf_Cocinero1)
                    .addComponent(tf_Cocinero3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_Cocinero2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_Empleado1)
                    .addComponent(tf_Empleado2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tb_EstadoEmpleado2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(tb_EstadoEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tb_EstadoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Contenido)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_Cocinero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Cocinero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Cocinero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 225, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(tf_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(tb_EstadoEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_EstadoEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_EstadoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_EstadoEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_EstadoEmpleado1ActionPerformed
        // TODO add your handling code here:
        e1.setActivo(!tb_EstadoEmpleado1.isSelected());
    }//GEN-LAST:event_tb_EstadoEmpleado1ActionPerformed

    private void tb_EstadoEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_EstadoEmpleado2ActionPerformed
        // TODO add your handling code here:
        e2.setActivo(!tb_EstadoEmpleado2.isSelected());
    }//GEN-LAST:event_tb_EstadoEmpleado2ActionPerformed

    private void tb_EstadoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_EstadoSistemaActionPerformed
        // TODO add your handling code here:
        e1.setActivo(!tb_EstadoSistema.isSelected());
        e2.setActivo(!tb_EstadoSistema.isSelected());
        c1.setEstado(!tb_EstadoSistema.isSelected());
        c2.setEstado(!tb_EstadoSistema.isSelected());
        c3.setEstado(!tb_EstadoSistema.isSelected());
        tb_EstadoEmpleado1.setSelected(tb_EstadoSistema.isSelected());
        tb_EstadoEmpleado2.setSelected(tb_EstadoSistema.isSelected());
    }//GEN-LAST:event_tb_EstadoSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante_P1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Contenido;
    private javax.swing.JTextArea ta_MesaPlatos;
    private javax.swing.JTextArea ta_MostradorPedidos;
    private javax.swing.JToggleButton tb_EstadoEmpleado1;
    private javax.swing.JToggleButton tb_EstadoEmpleado2;
    private javax.swing.JToggleButton tb_EstadoSistema;
    private javax.swing.JTextField tf_Cocinero1;
    private javax.swing.JTextField tf_Cocinero2;
    private javax.swing.JTextField tf_Cocinero3;
    private javax.swing.JTextField tf_Empleado1;
    private javax.swing.JTextField tf_Empleado2;
    // End of variables declaration//GEN-END:variables
}
